"""add course_grading_rules table for best-of-N policy

Revision ID: 9094581d7fe3
Revises: b3edef175733
Create Date: 2026-06-21 05:45:18.954749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9094581d7fe3'
down_revision: Union[str, None] = 'b3edef175733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_grading_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('best_of_group', sa.String(length=32), nullable=False),
    sa.Column('best_of_count', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'best_of_group', name='uq_grading_rule_course_group')
    )
    op.create_index(op.f('ix_course_grading_rules_course_id'), 'course_grading_rules', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_grading_rules_course_id'), table_name='course_grading_rules')
    op.drop_table('course_grading_rules')
    # ### end Alembic commands ###
